package Sqr;

/**
 * Sqr/Sqr_interfaceOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Sqr.idl Thursday, March 17, 2016 9:58:48 AM
 * IST
 */
public interface Sqr_interfaceOperations {

    int findSqr(int n);
} // interface Sqr_interfaceOperations
