package Sqr;

/**
 * Sqr/Sqr_interfaceHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Sqr.idl Thursday, March 17, 2016 9:58:48 AM
 * IST
 */
public final class Sqr_interfaceHolder implements org.omg.CORBA.portable.Streamable {

    public Sqr.Sqr_interface value = null;

    public Sqr_interfaceHolder() {
    }

    public Sqr_interfaceHolder(Sqr.Sqr_interface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = Sqr.Sqr_interfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        Sqr.Sqr_interfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return Sqr.Sqr_interfaceHelper.type();
    }

}
