package Sqr;

/**
 * Sqr/Sqr_interfaceHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Sqr.idl Thursday, March 17, 2016 9:58:48 AM
 * IST
 */
abstract public class Sqr_interfaceHelper {

    private static String _id = "IDL:Sqr/Sqr_interface:1.0";

    public static void insert(org.omg.CORBA.Any a, Sqr.Sqr_interface that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static Sqr.Sqr_interface extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(Sqr.Sqr_interfaceHelper.id(), "Sqr_interface");
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static Sqr.Sqr_interface read(org.omg.CORBA.portable.InputStream istream) {
        return narrow(istream.read_Object(_Sqr_interfaceStub.class));
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, Sqr.Sqr_interface value) {
        ostream.write_Object((org.omg.CORBA.Object) value);
    }

    public static Sqr.Sqr_interface narrow(org.omg.CORBA.Object obj) {
        if (obj == null) {
            return null;
        } else if (obj instanceof Sqr.Sqr_interface) {
            return (Sqr.Sqr_interface) obj;
        } else if (!obj._is_a(id())) {
            throw new org.omg.CORBA.BAD_PARAM();
        } else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            Sqr._Sqr_interfaceStub stub = new Sqr._Sqr_interfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static Sqr.Sqr_interface unchecked_narrow(org.omg.CORBA.Object obj) {
        if (obj == null) {
            return null;
        } else if (obj instanceof Sqr.Sqr_interface) {
            return (Sqr.Sqr_interface) obj;
        } else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            Sqr._Sqr_interfaceStub stub = new Sqr._Sqr_interfaceStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

}
