package Sqr;

/**
 * Sqr/Sqr_interface.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from Sqr.idl Thursday, March 17, 2016 9:58:48 AM IST
 */
public interface Sqr_interface extends Sqr_interfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface Sqr_interface
